### ISSUE TITLE
Configuration error with valid configuration

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-auth-dotnet#12] opened 2019-01-25 18:30 UTC
This code throws an exception:

```csharp
using Okta.Auth.Sdk;
using Okta.Sdk.Abstractions.Configuration;

namespace DotnetAuthSdkTester
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = new AuthenticationClient(new OktaClientConfiguration
            {
                OktaDomain = "https://dotnet.oktapreview.com",
                Token = "abc123notreal"
            });
        }
    }
}
```

The exception is:
> **System.ArgumentNullException:** 'Your Okta URL is missing. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain
Parameter name: OktaDomain'

**Comment by gitvinit** [comment] 2019-02-06 22:16
@nbarbettini @laura-rodriguez it seems the parameters aren't being passed to the base class BaseOktaClient constructor from AuthenticationClient constructor which is causing this exception. I can submit a PR if this hasn't been fixed yet

**Comment by laura-rodriguez** [comment] 2019-02-06 22:36
Hi @gitvinit ,
I was working with the `Okta.Auth.Sdk` by creating a new ASP.NET 4.x example and I was not able to reproduce this issue.

Can you please try with the sample and tell me if you are still facing this issue?
The project is in the `primary-auth` folder in the following branch: https://github.com/okta/samples-aspnet/tree/add-authn-sample
(waiting for approval to be merged).

You can replace the placeholders with your Okta configuration in the `Web.Config` or plug your values directly in the following code in the `UnityConfig.cs` file:
```
container.RegisterType<IAuthenticationClient>(new InjectionFactory(o => new AuthenticationClient(
                new OktaClientConfiguration()
                {
                    OktaDomain = ConfigurationManager.AppSettings["okta:OktaDomain"],
                    Token = ConfigurationManager.AppSettings["okta:Token"],
                })));
```

**Comment by gitvinit** [comment] 2019-02-06 23:26
Hi @laura-rodriguez the sample works fine. Ill tell you the steps I followed so you can reproduce the issue. 
I just created a simple console app program and referenced the auth sdk and used the code nbarbettini used above and it throws the validation exception. 
I am working on the auth-sdk from the master branch. 

The problem I see is the code nate is using will call the following constructor in AuthenticationClient
`public AuthenticationClient(OktaClientConfiguration apiClientConfiguration = null, ILogger logger = null)
        {
        }`
which inturn calls the constructor
`public BaseOktaClient(OktaClientConfiguration apiClientConfiguration = null, ILogger logger = null)`
however the apiClientConfiguration parameter is not passed to the base constructor which defaults to null and throws an exception at `OktaClientConfigurationValidator.Validate(Configuration)` in the base class constructor.
 
Please correct me if I am missing anything.

**Comment by laura-rodriguez** [comment] 2019-02-07 17:29
Hi @gitvinit,
You are right, thanks for providing the details of what's going here 💯 

If you are still up you can submit a PR. You will have to sign our contributor license agreement (https://developer.okta.com/cla/). All contributions are welcome 😄 
Otherwise, I will be able to fix this these days, I'd say by the end of the next week just to be safe.

Thanks!

**Comment by gitvinit** [comment] 2019-02-11 22:07
Ill be glad to submit a PR ill sign and submit the CLA as well.

**Closed** 2019-02-26 18:54 UTC
Labels: bug

**Comment by toro705** [comment] 2019-09-25 14:47
any news on this?
